// A complete Tibetan syllable, which always has a central root character,
// and may optionally also have a prefix, superscript, subscript, & up to two suffixes.
pub struct TibetanSyllable<'a> {
    pub root: &'a TibetanCharacter,
    pub prefix: Option<&'a TibetanCharacter>,
    pub superscript: Option<&'a TibetanCharacter>,
    pub subscript: Option<&'a TibetanCharacter>,
    pub suffix: Option<&'a TibetanCharacter>,
    pub second_suffix: Option<&'a TibetanCharacter>,
}

// A single Tibetan character, which may be a stand-alone syllable, or a part of one.
#[derive(Debug)]
pub struct TibetanCharacter {
    pub tibetan: char,
    pub wylie: &'static str,
    pub phonetic: &'static str,
    pub phonetic_as_suffix: &'static str,
    pub phonetic_modified_third_column: &'static str,
    pub unicode_code_point: char,
    pub unicode_code_point_as_subscript: char,
    pub column: Column,
}

// Returns the available subscripts for the given character.
impl TibetanCharacter {
    pub fn available_subscripts(&self) -> Vec<char> {
        match self.tibetan {
            'ཀ' => vec!['ཡ', 'ར', 'ལ'],
            'ཁ' => vec!['ཡ', 'ར'],
            'ག' => vec!['ཡ', 'ར', 'ལ'],
            'པ' => vec!['ཡ', 'ར', 'ལ'],
            'ཕ' => vec!['ཡ', 'ར'],
            'བ' => vec!['ཡ', 'ར'],
            'མ' => vec!['ཡ', 'ར'],
            'ཏ' => vec!['ར'],
            'ཐ' => vec!['ར'],
            'ད' => vec!['ར'],
            'ཤ' => vec!['ར'],
            'ར' => vec!['ལ'],
            'ས' => vec!['ར', 'ལ'],
            'ཟ' => vec!['ལ'],
            'ཧ' => vec!['ར'],
            _ => vec![],
        }
    }
}

// What column a character is found in, in the Tibetan alphabet table.
#[derive(Debug, PartialEq)]
pub enum Column {
    FIRST,
    SECOND,
    THIRD,
    FOURTH,
    NONE,
}

// A syllable/character's tone.
#[derive(Debug, PartialEq, Clone, Copy)]
pub enum Tone {
    HIGH,
    LOW,
    MID,
    NONE,
}

pub const DIAIRESIS_UNICODE_CODE_POINT: char = '\u{0308}';
pub const HIGH_TONE_UNICODE_CODE_POINT: char = '\u{0301}';
pub const LOW_TONE_UNICODE_CODE_POINT: char = '\u{0300}';

// All 30 Tibetan consonants.
pub const ROOTS: [TibetanCharacter; 30] = [
    TibetanCharacter {
        tibetan: 'ཀ',
        wylie: "ka",
        phonetic: "ka",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F40}',
        unicode_code_point_as_subscript: '\u{0F90}',
        column: Column::FIRST,
    },
    TibetanCharacter {
        tibetan: 'ཅ',
        wylie: "ca",
        phonetic: "ca",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F45}',
        unicode_code_point_as_subscript: '\u{0F95}',
        column: Column::FIRST,
    },
    TibetanCharacter {
        tibetan: 'ཏ',
        wylie: "ta",
        phonetic: "ta",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F4F}',
        unicode_code_point_as_subscript: '\u{0F9F}',
        column: Column::FIRST,
    },
    TibetanCharacter {
        tibetan: 'པ',
        wylie: "pa",
        phonetic: "pa",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F54}',
        unicode_code_point_as_subscript: '\u{0FA4}',
        column: Column::FIRST,
    },
    TibetanCharacter {
        tibetan: 'ཙ',
        wylie: "tsa",
        phonetic: "tsa",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F59}',
        unicode_code_point_as_subscript: '\u{0FA9}',
        column: Column::FIRST,
    },
    TibetanCharacter {
        tibetan: 'ཞ',
        wylie: "zha",
        phonetic: "zha",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F5E}',
        unicode_code_point_as_subscript: '\u{0FAE}',
        column: Column::NONE,
    },
    TibetanCharacter {
        tibetan: 'ར',
        wylie: "ra",
        phonetic: "ra",
        phonetic_as_suffix: "r",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F62}',
        unicode_code_point_as_subscript: '\u{0FB2}',
        column: Column::NONE,
    },
    TibetanCharacter {
        tibetan: 'ཧ',
        wylie: "ha",
        phonetic: "ha",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F67}',
        unicode_code_point_as_subscript: '\u{0FB7}',
        column: Column::NONE,
    },
    TibetanCharacter {
        tibetan: 'ཁ',
        wylie: "kha",
        phonetic: "kha",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F41}',
        unicode_code_point_as_subscript: '\u{0F91}',
        column: Column::SECOND,
    },
    TibetanCharacter {
        tibetan: 'ཆ',
        wylie: "cha",
        phonetic: "cha",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F46}',
        unicode_code_point_as_subscript: '\u{0F96}',
        column: Column::SECOND,
    },
    TibetanCharacter {
        tibetan: 'ཐ',
        wylie: "tha",
        phonetic: "tha",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F50}',
        unicode_code_point_as_subscript: '\u{0FA0}',
        column: Column::SECOND,
    },
    TibetanCharacter {
        tibetan: 'ཕ',
        wylie: "pha",
        phonetic: "pha",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F55}',
        unicode_code_point_as_subscript: '\u{0FA5}',
        column: Column::SECOND,
    },
    TibetanCharacter {
        tibetan: 'ཚ',
        wylie: "tsha",
        phonetic: "tsha",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F5A}',
        unicode_code_point_as_subscript: '\u{0FAA}',
        column: Column::SECOND,
    },
    TibetanCharacter {
        tibetan: 'ཟ',
        wylie: "za",
        phonetic: "za",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F5F}',
        unicode_code_point_as_subscript: '\u{0FAF}',
        column: Column::NONE,
    },
    TibetanCharacter {
        tibetan: 'ལ',
        wylie: "la",
        phonetic: "la",
        phonetic_as_suffix: "l",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F63}',
        unicode_code_point_as_subscript: '\u{0FB3}',
        column: Column::NONE,
    },
    TibetanCharacter {
        tibetan: 'ཨ',
        wylie: "a",
        phonetic: "a",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F68}',
        unicode_code_point_as_subscript: '\u{0FB8}',
        column: Column::NONE,
    },
    TibetanCharacter {
        tibetan: 'ག',
        wylie: "ga",
        phonetic: "kha",
        phonetic_as_suffix: "k",
        phonetic_modified_third_column: "ga",
        unicode_code_point: '\u{0F42}',
        unicode_code_point_as_subscript: '\u{0F92}',
        column: Column::THIRD,
    },
    TibetanCharacter {
        tibetan: 'ཇ',
        wylie: "ja",
        phonetic: "cha",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "ja",
        unicode_code_point: '\u{0F47}',
        unicode_code_point_as_subscript: '\u{0F97}',
        column: Column::THIRD,
    },
    TibetanCharacter {
        tibetan: 'ད',
        wylie: "da",
        phonetic: "tha",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "da",
        unicode_code_point: '\u{0F51}',
        unicode_code_point_as_subscript: '\u{0FA1}',
        column: Column::THIRD,
    },
    TibetanCharacter {
        tibetan: 'བ',
        wylie: "ba",
        phonetic: "pha",
        phonetic_as_suffix: "p",
        phonetic_modified_third_column: "ba",
        unicode_code_point: '\u{0F56}',
        unicode_code_point_as_subscript: '\u{0FA6}',
        column: Column::THIRD,
    },
    TibetanCharacter {
        tibetan: 'ཛ',
        wylie: "dza",
        phonetic: "dza",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "dza",
        unicode_code_point: '\u{0F5B}',
        unicode_code_point_as_subscript: '\u{0FAB}',
        column: Column::THIRD,
    },
    TibetanCharacter {
        tibetan: 'འ',
        wylie: "'a",
        phonetic: "a",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F60}',
        unicode_code_point_as_subscript: '\u{0FB0}',
        column: Column::NONE,
    },
    TibetanCharacter {
        tibetan: 'ཤ',
        wylie: "sha",
        phonetic: "sha",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F64}',
        unicode_code_point_as_subscript: '\u{0FB4}',
        column: Column::NONE,
    },
    TibetanCharacter {
        tibetan: 'ང',
        wylie: "nga",
        phonetic: "nga",
        phonetic_as_suffix: "ng",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F44}',
        unicode_code_point_as_subscript: '\u{0F94}',
        column: Column::FOURTH,
    },
    TibetanCharacter {
        tibetan: 'ཉ',
        wylie: "nya",
        phonetic: "nya",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F49}',
        unicode_code_point_as_subscript: '\u{0F99}',
        column: Column::FOURTH,
    },
    TibetanCharacter {
        tibetan: 'ན',
        wylie: "na",
        phonetic: "na",
        phonetic_as_suffix: "n",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F53}',
        unicode_code_point_as_subscript: '\u{0FA3}',
        column: Column::FOURTH,
    },
    TibetanCharacter {
        tibetan: 'མ',
        wylie: "ma",
        phonetic: "ma",
        phonetic_as_suffix: "m",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F58}',
        unicode_code_point_as_subscript: '\u{0FA8}',
        column: Column::FOURTH,
    },
    TibetanCharacter {
        tibetan: 'ཝ',
        wylie: "wa",
        phonetic: "wa",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F5D}',
        unicode_code_point_as_subscript: '\u{0FAD}',
        column: Column::NONE, // TODO: FOURTH or NONE?
    },
    TibetanCharacter {
        tibetan: 'ཡ',
        wylie: "ya",
        phonetic: "ya",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F61}',
        unicode_code_point_as_subscript: '\u{0FB1}',
        column: Column::NONE,
    },
    TibetanCharacter {
        tibetan: 'ས',
        wylie: "sa",
        phonetic: "sa",
        phonetic_as_suffix: "",
        phonetic_modified_third_column: "",
        unicode_code_point: '\u{0F66}',
        unicode_code_point_as_subscript: '\u{0FB6}',
        column: Column::NONE,
    },
];

pub const SUPERSCRIPTS: [char; 3] = ['ར', 'ལ', 'ས'];

pub const PREFIXES: [char; 5] = ['ག', 'ད', 'བ', 'མ', 'འ'];

pub const SUFFIXES: [char; 10] = ['ག', 'ང', 'ད', 'ན', 'བ', 'མ', 'འ', 'ར', 'ལ', 'ས'];

pub const SUFFIXES_THAT_CAUSE_VOWEL_CHANGE: [char; 4] = ['ད', 'ན', 'ལ', 'ས'];

pub const SECOND_SUFFIXES: [char; 2] = ['ད', 'ས'];
